spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.7.112:3306/my_db
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #\u5F00\u542F\u9A7C\u5CF0\u8F6C\u6362
    map-underscore-to-camel-case: true
    # \u5F00\u542F\u5EF6\u8FDF\u61D2\u52A0\u8F7D\uFF08\u5168\u5C40\u914D\u7F6E\uFF09
    lazy-loading-enabled: true
    # \u6309\u9700\u52A0\u8F7D
    aggressive-lazy-loading: false
    # \u5173\u952E\uFF1A\u6E05\u7A7A\u89E6\u53D1\u65B9\u6CD5
    lazy-load-trigger-methods: ""

# 日志配置
logging:
  level:
    # 替换为你的 Mapper 接口所在包（必须准确！）
    com.hxl.cache.mapper: DEBUG
    # 可选：MyBatis 核心包日志（若需查看更详细的 MyBatis 内部日志）
    org.apache.ibatis: DEBUG